server:
  port: 8083

spring:
  datasource:
#    인메모리
#    url: jdbc:h2:mem:testdb
#    서버모드
    url: jdbc:h2:tcp://localhost/~/testDB
#    파일 모드
#    url: jdbc:h2:~/testDB
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console


logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
